-- main engine file --

local lib = {}
local input = require("rce.input")

function lib.userenderer(id)
  lib.renderer = require("rce.renderers."..id)
end

lib.useinputscheme = input.useinputs

function lib.newstate()
  local state = {}
  lib.renderer.init(state)
  return state
end

-- preblit is a table of "drawable" textures generated by textures.todrawable
function lib.render(state, preblit)
  local start = os.epoch("utc")
  lib.renderer.renderFrame(state, preblit)
  return os.epoch("utc") - start
end

return lib
